name: my-app

networks:
  my-network:
    driver: bridge

services:
  my-nginx:
    build: 
      context: nginx/
    ports:
      - "8000:80"
      - "8001:81"
    networks:
      - my-network

  my-golang:
    build: 
      context: golang/
    ports:
      - "8080:80"
    networks:
      - my-network